Add pre commit hooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -13,7 +13,10 @@ then
     exit 1
 fi
 
+
 #!/bin/sh
+echo "PRETTIFYING FILES"
+
 FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
 [ -z "$FILES" ] && exit 0
 
@@ -23,12 +26,13 @@ echo "$FILES" | xargs ./frontend/node_modules/.bin/prettier --ignore-unknown --w
 # Add back the modified/prettified files to staging
 echo "$FILES" | xargs git add
 
-exit 0
+echo "PRETTIFY SUCCESSFUL"
 
 
 #!/bin/bash
+echo "ESLINT'ing files......"
 cd "$(git rev-parse --show-toplevel)"
-ESLINT="./frontedn/node_modules/.bin/eslint"
+ESLINT="./frontend/node_modules/.bin/eslint"
 pwd
 
 if [[ ! -x "$ESLINT" ]]; then
@@ -49,4 +53,15 @@ $ESLINT "${STAGED_FILES[@]}" --fix
 ESLINT_EXIT="$?"
 
 # Re-add files since they may have been fixed
-git add "${S
+git add "${STAGED_FILES[@]}"
+
+if [[ "${ESLINT_EXIT}" == 0 ]]; then
+  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
+else
+  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
+  exit 1
+fi
+
+echo "ESLINT SUCCESSFUL!"
+exit $?
+
